name: CI Pipeline

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run script
      run: |
        # Vérifie si test_folder existe, sinon utilise un dossier temporaire
        if [ -d "test_folder" ]; then
          python log_analyzer.py test_folder
        else
          mkdir -p test_temp
          echo "test" > test_temp/file1.txt
          echo "test" > test_temp/file2.txt
          echo "autre" > test_temp/file3.txt
          python log_analyzer.py test_temp
          rm -rf test_temp
        fi
      env:
        PYTHONUNBUFFERED: 1

    - name: Verify output
      run: |
        if [ -f "rapport.txt" ]; then
          echo "Script executed successfully, rapport.txt found."
        else
          echo "Error: rapport.txt not generated."
          exit 1
        fi